### ISSUE TITLE
`next-error` does not look at new compilation run

### ISSUE THREAD

**Issue by adelbertc** [hvesalai/emacs-sbt-mode#32]
For instance, when I run `sbt ~compile` and I get say, 5 errors, I will jump to (`next-error`) and fix the first one and save again. This will trigger a new compilation, and perhaps will display some new errors. Hitting `next-error` then gives me the next error from the previous compilation run, not the new one.

**Comment by hvesalai** [comment]
This is true. It is a bit tricky thing to fix and I welcome all pull requests to that end.

Meanwhile I do it this way. Instead of using `~compile`, I use `C-x '` to run `sbt-run-previous-command`. This will save all the buffers and run `test:compile` by default clearing the sbt-buffer and also reseting the `next-error` pointer.

Read more from: https://github.com/hvesalai/sbt-mode#compilation

**Comment by adelbertc** [comment]
Ah cool - I just added a `after-save-hook` in `sbt-mode` that runs `sbt-run-previous-command` on save.

```
(add-hook 'sbt-mode-hook'(lambda ()
    (add-hook 'after-save-hook 'sbt-run-previous-command)
))
```

**Comment by fommil** [comment]
@adelbertc another approach could be to limit errors in sbt to just one at a time. Although I must admit I prefer your save hook approach as I've never really trusted `sbt ~compile`.

**Comment by fommil** [comment]
the `compile` support in emacs is magical, there is probably some incantation to move the point to the last error. @adelbertc could you please have a look into this?

**Comment by hvesalai** [comment]
What this actually needs is a way to reset the next-error pointer when ever `~` fires the compilation so that only the errors that occur in the latest run are considered.

**Comment by hvesalai** [comment]
I'll close this. A PR to enhance emacs-sbt-mode is welcomed if somebody really wants to fix this.
